const sourceNames=`信報財經新聞|Finance730|香港經濟日報 HKET|香港財經時報 HKBT|新城財經台|香港金融管理局|游庭皓的財經皓角|柴鼠兄弟 ZRBros|风傳媒-下班经济學|老王愛說笑|SHIN LI|自由女神邱沁宜|Better Leaf 好葉|慢活夫妻 George & Dewi|大俠武林|股乾爹 KuKanTieh|Gooaye股癌|理財不能等|懶錢包LazyWallet|M觀點|蕾咪Rami|財經 M 平方 MacroMicro|元大投顧財金頻道|股海老牛|财经风云|视野环球财经|阳光财经|ChineseFN 中文投資網|财经全世界|王剑财经观察|老李玩钱|土妹发财|贝拉说美股|美投说美股|艾爾文|寶可孟の省錢大作戰|吳淡如人生實用商學院|郭哲榮分析師|央视财经|Bloomberg中国|肖恩|老徐价值投资|小Lin说|CK财经频道|钱姐说钱|硅谷居士|Mr.Market市场先生|财报狗|天下杂志|商业周刊|今周刊|非凡财经新闻|东森财经新闻|第一财经|FT中文网|BBC News 中文|德国之声中文|美国之音中文网|自由亚洲电台|观视频工作室|睡前消息|曲博科技教室`.split('|');
const box=document.querySelector('#channels');
box.innerHTML=sourceNames.map((n,i)=>`<label class="channel"><input type="checkbox" value="${n}" ${i<4?'checked':''}> ${n}</label>`).join('');
const checked=()=>[...box.querySelectorAll(':checked')].map(x=>x.value);
const count=()=>document.querySelector('#count').textContent=`// ${checked().length} SELECTED`;
box.onchange=count; count();
document.querySelector('#all').onclick=()=>{const all=checked().length===sourceNames.length;box.querySelectorAll('input').forEach(x=>x.checked=!all);count()};
let last=[];
function esc(s=''){return s.replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function render(items){const out=document.querySelector('#results');document.querySelector('#empty').style.display='none';out.innerHTML=items.map(x=>x.error?`<article class="item error"><div class="meta">${esc(x.channel)} · SCAN ERROR</div><h3>未完成读取</h3><p class="tag">${esc(x.error)}</p></article>`:`<article class="item"><div class="meta">${esc(x.channel)} · ${esc(x.published)} · ${esc(x.status)}</div><h3><a href="${x.url}" target="_blank" rel="noreferrer">${esc(x.title)}</a></h3>${x.transcript?`<div class="transcript">${esc(x.transcript)}</div>`:'<p class="tag">该视频未能读取公开中文字幕。请通过标题链接观看原视频。</p>'}</article>`).join('')}
document.querySelector('#scan').onclick=async()=>{const channels=checked();if(!channels.length)return alert('请至少选择一个频道');if(channels.length>12)return alert('单次最多选择 12 个频道');const b=document.querySelector('#scan'), p=document.querySelector('#progress'),state=document.querySelector('#state');b.disabled=true;p.style.width='25%';state.textContent='正在连接 YouTube…';try{const r=await fetch('/api/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channels})});const data=await r.json();if(!r.ok)throw Error(data.error);last=data.items;p.style.width='100%';state.textContent='扫描完成';document.querySelector('#stamp').textContent='LAST RUN · '+new Date(data.fetchedAt).toLocaleString('zh-CN');render(last);document.querySelector('#push').disabled=false}catch(e){state.textContent='执行失败';alert('扫描失败：'+e.message)}finally{b.disabled=false;setTimeout(()=>p.style.width='0',1200)}};
document.querySelector('#runflows').onclick=async()=>{const b=document.querySelector('#runflows'),msg=document.querySelector('#flowsmsg');b.disabled=true;msg.textContent='正在触发 GitHub Actions…';try{const r=await fetch('/api/run-flows',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const d=await r.json();if(!r.ok)throw Error(d.error);msg.textContent='已触发 workflow_dispatch（HTTP '+d.status+'）'}catch(e){msg.textContent='触发失败：'+e.message}finally{b.disabled=false}};
document.querySelector('#push').onclick=async()=>{const token=document.querySelector('#token').value.trim();if(!token)return alert('请输入 PushPlus Token');const content=`<h2>SIGNAL ARCADE · 财经情报简报</h2>${document.querySelector('#results').innerHTML}<p>仅作研究参考，不构成投资建议。</p>`;const b=document.querySelector('#push');b.disabled=true;try{const r=await fetch('/api/push',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,content})});const d=await r.json();if(!r.ok||d.code&&d.code!==200)throw Error(d.msg||d.error);alert('已推送至 PushPlus。')}catch(e){alert('推送失败：'+e.message)}finally{b.disabled=false}};
